"""
CAD and Blender export utilities.

Formats:
  STL   — binary mesh (already in holder.py)
  OBJ   — Wavefront mesh (widely supported by CAD tools)
  Blender Python script — run inside Blender to recreate the full scene
  .blend — generated by running Blender headlessly
"""

import os
import json
import struct
import subprocess
import tempfile
import textwrap
import numpy as np


BLENDER_PATHS = [
    r"C:\Program Files\Blender Foundation\Blender 5.0\blender.exe",
    r"C:\Program Files\Blender Foundation\Blender 4.3\blender.exe",
    r"C:\Program Files\Blender Foundation\Blender 4.2\blender.exe",
    r"/usr/bin/blender",
    r"/Applications/Blender.app/Contents/MacOS/Blender",
    "blender",
]

_AXIS_COLORS_BLENDER = {
    "Gx": (0.9, 0.3, 0.1, 1.0),   # orange-red
    "Gy": (0.1, 0.6, 0.2, 1.0),   # green
    "Gz": (0.1, 0.3, 0.9, 1.0),   # blue
}

_HOLDER_COLORS = {
    "Gx": (1.0, 0.55, 0.0, 0.35),
    "Gy": (0.1, 0.6, 0.2, 0.30),
    "Gz": (0.1, 0.3, 0.9, 0.25),
}


# ─────────────────────────────────────────────────────────────────────────────
# OBJ export
# ─────────────────────────────────────────────────────────────────────────────

def holder_to_obj(holder, n_phi=300, n_x=200) -> str:
    """Generate Wavefront OBJ text for a holder mesh (no MTL)."""
    verts_mm, faces = _holder_mesh_data(holder, n_phi=n_phi, n_x=n_x, groove_scale=3.0)

    lines = [
        f"# Gradient coil holder [{holder.label}]",
        f"# R={holder.R:.1f}mm  OD={holder.R_outer*2:.1f}mm  length={holder.length:.0f}mm",
        "o holder_" + holder.label,
    ]
    for v in verts_mm:
        lines.append(f"v {v[0]:.4f} {v[1]:.4f} {v[2]:.4f}")
    for f in faces:
        # OBJ is 1-indexed; quads → two triangles
        a, b, c, d = [idx + 1 for idx in f]
        lines.append(f"f {a} {b} {c}")
        lines.append(f"f {a} {c} {d}")
    return "\n".join(lines) + "\n"


def save_obj(holder, filepath, **kwargs):
    """Write holder to OBJ file."""
    with open(filepath, "w") as fh:
        fh.write(holder_to_obj(holder, **kwargs))


def save_all_obj(result, output_dir):
    """Write OBJ files for all coil holders."""
    os.makedirs(output_dir, exist_ok=True)
    paths = {}
    for lbl, info in result["coils"].items():
        p = os.path.join(output_dir, f"{lbl}_holder.obj")
        save_obj(info["holder"], p)
        paths[lbl] = p
    return paths


# ─────────────────────────────────────────────────────────────────────────────
# Blender Python script generation
# ─────────────────────────────────────────────────────────────────────────────

def _grid_quads(nr, nc, flip=False):
    """Return quad face list for an (nr × nc) vertex grid.

    Adds a wrap-around column connecting the last phi column back to the
    first, closing the cylinder.  Assumes endpoint=False phi grid.
    """
    faces = []
    for i in range(nr - 1):
        # Interior columns
        for j in range(nc - 1):
            v00 = i * nc + j
            v10 = (i + 1) * nc + j
            v01 = i * nc + (j + 1)
            v11 = (i + 1) * nc + (j + 1)
            if not flip:
                faces.append([v00, v10, v11, v01])
            else:
                faces.append([v00, v01, v11, v10])
        # Wrap-around: last column → first column
        v00 = i * nc + (nc - 1)
        v10 = (i + 1) * nc + (nc - 1)
        v01 = i * nc + 0
        v11 = (i + 1) * nc + 0
        if not flip:
            faces.append([v00, v10, v11, v01])
        else:
            faces.append([v00, v01, v11, v10])
    return faces


def _annulus_quads(x_pos, r_inner, r_outer, n_phi, flip=False):
    """Vertex list + face list for a flat annulus at x_pos (mm).

    Uses endpoint=False phi grid to match surface grids.
    """
    phi = np.linspace(-np.pi, np.pi, n_phi, endpoint=False)
    verts = []
    for p in phi:
        verts.append([x_pos, r_inner * np.cos(p), r_inner * np.sin(p)])
    for p in phi:
        verts.append([x_pos, r_outer * np.cos(p), r_outer * np.sin(p)])
    faces = []
    for i in range(n_phi):
        ni = (i + 1) % n_phi   # wrap-around on last vertex
        i_in, ni_in = i, ni
        i_out, ni_out = i + n_phi, ni + n_phi
        if not flip:
            faces.append([i_in, ni_in, ni_out, i_out])
        else:
            faces.append([i_in, i_out, ni_out, ni_in])
    return verts, faces


def _band_quads(x0, x1, R, n_phi, flip=False):
    """Axial band between two x positions at radius R (mm).

    Uses endpoint=False phi grid; wrap-around handled via modulo.
    """
    phi = np.linspace(-np.pi, np.pi, n_phi, endpoint=False)
    verts = []
    for p in phi:
        verts.append([x0, R * np.cos(p), R * np.sin(p)])
    for p in phi:
        verts.append([x1, R * np.cos(p), R * np.sin(p)])
    faces = []
    for i in range(n_phi):
        ni = (i + 1) % n_phi   # wrap-around
        if not flip:
            faces.append([i, ni, ni + n_phi, i + n_phi])
        else:
            faces.append([i, i + n_phi, ni + n_phi, ni])
    return verts, faces


def _holder_mesh_data(holder, n_phi=300, n_x=200, groove_scale=3.0):
    """Return (verts_mm, faces) for the full holder shell.

    Mesh is built entirely in Python/numpy so it works inside Blender's
    embedded Python without scipy or any external library.
    """
    all_verts = []
    all_faces = []

    def add(verts, faces):
        offset = len(all_verts)
        all_verts.extend(verts)
        for f in faces:
            all_faces.append([idx + offset for idx in f])

    # ── Outer grooved surface ────────────────────────────────────────────────
    X_o, Y_o, Z_o, _ = holder.groove_surface(n_phi=n_phi, n_x=n_x, groove_scale=groove_scale)
    nr, nc = X_o.shape
    outer_verts = np.round(
        np.column_stack([X_o.ravel(), Y_o.ravel(), Z_o.ravel()]), 3
    ).tolist()
    add(outer_verts, _grid_quads(nr, nc, flip=True))   # outward +R normals

    # ── Inner bore surface ───────────────────────────────────────────────────
    phi_g = np.linspace(-np.pi, np.pi, n_phi, endpoint=False)
    x_g   = np.linspace(-holder.x_half, holder.x_half, n_x)
    PHI, XX = np.meshgrid(phi_g, x_g)
    inner_verts = np.round(np.column_stack([
        XX.ravel(),
        (holder.R_inner * np.cos(PHI)).ravel(),
        (holder.R_inner * np.sin(PHI)).ravel(),
    ]), 3).tolist()
    add(inner_verts, _grid_quads(nr, nc, flip=False))  # inward −R normals

    # ── End cap annuli ───────────────────────────────────────────────────────
    for x_sign in (-1, 1):
        v, f = _annulus_quads(
            x_sign * holder.x_half, holder.R_inner, holder.R_outer,
            n_phi, flip=(x_sign > 0)
        )
        add(v, f)

    # ── Flanges ──────────────────────────────────────────────────────────────
    if holder.flange_w > 0:
        for x_sign in (-1, 1):
            xb = holder.x_half
            xf = holder.x_half + holder.flange_w
            # Outer face of flange
            v, f = _annulus_quads(
                x_sign * xf, holder.R_inner, holder.R_flange,
                n_phi, flip=(x_sign < 0)
            )
            add(v, f)
            # Inner face of flange (ring between R_outer and R_flange)
            v, f = _annulus_quads(
                x_sign * xb, holder.R_outer, holder.R_flange,
                n_phi, flip=(x_sign > 0)
            )
            add(v, f)
            # Outer band of flange
            v, f = _band_quads(
                x_sign * xb, x_sign * xf, holder.R_flange,
                n_phi, flip=(x_sign < 0)
            )
            add(v, f)

    return all_verts, all_faces


def generate_blender_script(result, output_blend_path=None) -> str:
    """Return a self-contained Python script to recreate the scene in Blender.

    The script embeds pre-computed mesh data (vertices + quad faces) and wire
    paths as JSON, then builds everything with bpy.data.meshes.from_pydata().
    No external libraries or Blender import operators are needed.

    Run via:
      blender --background --python script.py
    or paste into Blender's Script Editor.
    """
    coil_data = {}
    for lbl, info in result["coils"].items():
        holder = info["holder"]
        verts_mm, faces = _holder_mesh_data(holder, n_phi=300, n_x=200, groove_scale=3.0)
        coil_data[lbl] = {
            "wires": [
                {"xyz": w["xyz"].tolist(), "level": float(w["level"])}
                for w in info["wires_3d"]
            ],
            "holder_verts_mm": verts_mm,
            "holder_faces": faces,
        }

    data_json = json.dumps(coil_data, separators=(",", ":"))

    output_line = ""
    if output_blend_path:
        safe = output_blend_path.replace("\\", "\\\\")
        output_line = f'bpy.ops.wm.save_as_mainfile(filepath=r"{safe}")'

    script = textwrap.dedent(f"""\
    # Gradient Coil Designer — Auto-generated Blender scene
    # Coordinate convention: X = bore axis, Y = B0, Z = perpendicular
    # Run: blender --background --python <this_file>
    import bpy, json, math

    # ── Scene reset ─────────────────────────────────────────────────────────
    bpy.ops.object.select_all(action='SELECT')
    bpy.ops.object.delete(use_global=False)
    for d in (bpy.data.meshes, bpy.data.curves, bpy.data.materials):
        for blk in list(d):
            try: d.remove(blk)
            except Exception: pass

    # ── Embedded data ────────────────────────────────────────────────────────
    COIL_DATA = json.loads({repr(data_json)})

    WIRE_COLORS = {{
        "Gx": {{"pos": (0.90, 0.25, 0.05), "neg": (0.20, 0.40, 0.90)}},
        "Gy": {{"pos": (0.05, 0.65, 0.15), "neg": (0.55, 0.85, 0.10)}},
        "Gz": {{"pos": (0.90, 0.50, 0.00), "neg": (0.95, 0.80, 0.00)}},
    }}
    HOLDER_COLORS = {{
        "Gx": (1.00, 0.55, 0.00),
        "Gy": (0.10, 0.65, 0.20),
        "Gz": (0.15, 0.35, 0.90),
    }}

    # ── Helpers ──────────────────────────────────────────────────────────────
    def make_mat(name, rgb, alpha=1.0, metallic=0.0, roughness=0.45):
        mat = bpy.data.materials.new(name)
        mat.use_nodes = True
        nt = mat.node_tree
        bsdf = nt.nodes.get("Principled BSDF")
        if bsdf:
            bsdf.inputs["Base Color"].default_value = (*rgb, 1.0)
            bsdf.inputs["Alpha"].default_value = alpha
            bsdf.inputs["Metallic"].default_value = metallic
            bsdf.inputs["Roughness"].default_value = roughness
        if alpha < 1.0:
            # Blender 4.2+: blend_method / shadow_method removed; use surface_render_method
            if hasattr(mat, "surface_render_method"):
                mat.surface_render_method = "BLENDED"
            elif hasattr(mat, "blend_method"):
                mat.blend_method = "BLEND"
        return mat

    def build_mesh(name, verts_mm, faces, mat, col):
        \"\"\"Create a shaded mesh object from mm vertices + poly face list.\"\"\"
        mesh = bpy.data.meshes.new(name + "_mesh")
        # Convert mm → metres
        verts_m = [(v[0] * 0.001, v[1] * 0.001, v[2] * 0.001) for v in verts_mm]
        mesh.from_pydata(verts_m, [], faces)
        mesh.update()
        # Smooth shading on every polygon
        for poly in mesh.polygons:
            poly.use_smooth = True
        obj = bpy.data.objects.new(name, mesh)
        if mat:
            obj.data.materials.append(mat)
        col.objects.link(obj)
        return obj

    def add_wire(name, xyz_m, bevel_r_m, mat, col):
        \"\"\"Add a POLY curve object with bevel for wire tube rendering.\"\"\"
        crv = bpy.data.curves.new(name + "_crv", type="CURVE")
        crv.dimensions    = "3D"
        crv.bevel_depth   = bevel_r_m
        crv.bevel_resolution = 4
        crv.fill_mode     = "FULL"
        sp = crv.splines.new("POLY")
        sp.points.add(len(xyz_m) - 1)
        for i, pt in enumerate(xyz_m):
            sp.points[i].co = (pt[0], pt[1], pt[2], 1.0)
        obj = bpy.data.objects.new(name, crv)
        if mat:
            obj.data.materials.append(mat)
        col.objects.link(obj)
        return obj

    # ── Build scene ──────────────────────────────────────────────────────────
    root = bpy.context.scene.collection

    for label, data in COIL_DATA.items():
        wire_col = bpy.data.collections.new(label + "_Wires")
        hold_col = bpy.data.collections.new(label + "_Holder")
        root.children.link(wire_col)
        root.children.link(hold_col)

        # Wire tubes
        cols = WIRE_COLORS.get(label, {{"pos": (0.8,0.2,0.1), "neg": (0.2,0.3,0.8)}})
        for i, wd in enumerate(data["wires"]):
            rgb = cols["pos"] if wd["level"] > 0 else cols["neg"]
            mat = make_mat(f"{{label}}_w{{i}}_mat", rgb, metallic=0.85, roughness=0.15)
            add_wire(f"{{label}}_wire_{{i:02d}}", wd["xyz"], 0.00075, mat, wire_col)

        # Holder mesh (pre-computed grooved surface)
        hrgb = HOLDER_COLORS.get(label, (0.5, 0.5, 0.5))
        hmat = make_mat(label + "_holder_mat", hrgb, alpha=0.55, roughness=0.55)
        build_mesh(label + "_holder", data["holder_verts_mm"], data["holder_faces"],
                   hmat, hold_col)

    # ── Camera ───────────────────────────────────────────────────────────────
    bpy.ops.object.camera_add(location=(0.45, -0.38, 0.28))
    cam = bpy.context.active_object
    cam.rotation_euler = (math.radians(68), 0, math.radians(46))
    bpy.context.scene.camera = cam

    # ── Lighting ─────────────────────────────────────────────────────────────
    bpy.ops.object.light_add(type='SUN', location=(0.8, -0.6, 1.0))
    sun = bpy.context.active_object
    sun.data.energy = 4.0
    sun.rotation_euler = (math.radians(40), 0, math.radians(25))

    bpy.ops.object.light_add(type='AREA', location=(-0.4, 0.5, 0.6))
    area = bpy.context.active_object
    area.data.energy = 600.0
    area.data.size = 0.5

    # ── Render settings ──────────────────────────────────────────────────────
    bpy.context.scene.render.engine = 'CYCLES'
    bpy.context.scene.cycles.samples = 128

    print("Gradient coil scene built successfully.")

    # ── Save ─────────────────────────────────────────────────────────────────
    {output_line}
    """)
    return script


def save_blender_script(result, script_path):
    """Write the Blender import script to a .py file."""
    script = generate_blender_script(result)
    with open(script_path, "w", encoding="utf-8") as f:
        f.write(script)
    return script_path


# ─────────────────────────────────────────────────────────────────────────────
# Headless Blender .blend export
# ─────────────────────────────────────────────────────────────────────────────

def find_blender():
    """Return path to Blender executable, or None if not found."""
    for p in BLENDER_PATHS:
        if os.path.isfile(p):
            return p
        try:
            r = subprocess.run([p, "--version"], capture_output=True, timeout=5)
            if r.returncode == 0:
                return p
        except Exception:
            pass
    return None


def export_blend(result, blend_path, blender_exe=None, timeout=120,
                 progress_callback=None):
    """Generate a .blend file by running Blender headlessly.

    Parameters
    ----------
    result : dict
        Output of GradientCoilDesigner.run().
    blend_path : str
        Output .blend file path.
    blender_exe : str or None
        Path to blender.exe / blender binary.  Auto-detected if None.
    timeout : int
        Max seconds to wait for Blender.
    progress_callback : callable(str) or None
        Called with status strings during export.

    Returns
    -------
    str  — path to the written .blend file
    Raises RuntimeError if Blender is not found or fails.
    """
    def log(msg):
        if progress_callback:
            progress_callback(msg)
        else:
            print(msg)

    if blender_exe is None:
        blender_exe = find_blender()
    if blender_exe is None:
        raise RuntimeError(
            "Blender not found.  Install Blender or set blender_exe= manually."
        )

    log(f"Using Blender: {blender_exe}")
    os.makedirs(os.path.dirname(os.path.abspath(blend_path)), exist_ok=True)

    # Write script to a temp file
    script = generate_blender_script(result, output_blend_path=blend_path)
    with tempfile.NamedTemporaryFile(suffix=".py", delete=False,
                                     mode="w", encoding="utf-8") as tf:
        tf.write(script)
        script_file = tf.name

    log("Running Blender headlessly ...")
    try:
        proc = subprocess.run(
            [blender_exe, "--background", "--python", script_file],
            capture_output=True, text=True, timeout=timeout,
        )
        if proc.returncode != 0 or "Traceback" in proc.stderr:
            raise RuntimeError(
                f"Blender failed (exit {proc.returncode}).\n"
                f"stderr:\n{proc.stderr[-3000:]}"
            )
        log(f"Blend file written: {blend_path}")
    finally:
        try:
            os.unlink(script_file)
        except OSError:
            pass

    return blend_path
