"""
CAD and Blender export utilities.

Formats:
  STL   — binary mesh (already in holder.py)
  OBJ   — Wavefront mesh (widely supported by CAD tools)
  Blender Python script — run inside Blender to recreate the full scene
  .blend — generated by running Blender headlessly
"""

import os
import json
import struct
import subprocess
import tempfile
import textwrap
import numpy as np


BLENDER_PATHS = [
    r"C:\Program Files\Blender Foundation\Blender 5.0\blender.exe",
    r"C:\Program Files\Blender Foundation\Blender 4.3\blender.exe",
    r"C:\Program Files\Blender Foundation\Blender 4.2\blender.exe",
    r"/usr/bin/blender",
    r"/Applications/Blender.app/Contents/MacOS/Blender",
    "blender",
]

_AXIS_COLORS_BLENDER = {
    "Gx": (0.9, 0.3, 0.1, 1.0),   # orange-red
    "Gy": (0.1, 0.6, 0.2, 1.0),   # green
    "Gz": (0.1, 0.3, 0.9, 1.0),   # blue
}

_HOLDER_COLORS = {
    "Gx": (1.0, 0.55, 0.0, 0.35),
    "Gy": (0.1, 0.6, 0.2, 0.30),
    "Gz": (0.1, 0.3, 0.9, 0.25),
}


# ─────────────────────────────────────────────────────────────────────────────
# OBJ export
# ─────────────────────────────────────────────────────────────────────────────

def holder_to_obj(holder, n_phi=120, n_x=80) -> str:
    """Generate Wavefront OBJ text for a holder mesh (no MTL)."""
    from .holder import _surface_to_triangles, _annulus_triangles

    lines = [
        f"# Gradient coil holder [{holder.label}]",
        f"# R={holder.R:.1f}mm  OD={holder.R_outer*2:.1f}mm  length={holder.length:.0f}mm",
        "o holder_" + holder.label,
    ]

    verts = []
    faces = []
    v_offset = 1  # OBJ is 1-indexed

    def add_tris(triangles):
        nonlocal v_offset
        for tri in triangles:
            for v in tri:
                verts.append(v)
            n = len(verts)
            faces.append((n - 2, n - 1, n))   # 1-indexed, already offset

    # Outer grooved surface
    X, Y, Z, _ = holder.groove_surface(n_phi=n_phi, n_x=n_x)
    add_tris(_surface_to_triangles(X, Y, Z, flip=False))

    # Inner surface
    phi_g = np.linspace(-np.pi, np.pi, n_phi)
    x_g = np.linspace(-holder.x_half, holder.x_half, n_x)
    PHI, XX = np.meshgrid(phi_g, x_g)
    add_tris(_surface_to_triangles(XX, holder.R_inner * np.cos(PHI), holder.R_inner * np.sin(PHI), flip=True))

    # End caps
    for x_sign in [-1, 1]:
        add_tris(_annulus_triangles(x_sign * holder.x_half, holder.R_inner, holder.R_outer, n_phi, flip=(x_sign > 0)))

    for v in verts:
        lines.append(f"v {v[0]:.5f} {v[1]:.5f} {v[2]:.5f}")
    for f in faces:
        lines.append(f"f {f[0]} {f[1]} {f[2]}")

    return "\n".join(lines) + "\n"


def save_obj(holder, filepath, **kwargs):
    """Write holder to OBJ file."""
    with open(filepath, "w") as fh:
        fh.write(holder_to_obj(holder, **kwargs))


def save_all_obj(result, output_dir):
    """Write OBJ files for all coil holders."""
    os.makedirs(output_dir, exist_ok=True)
    paths = {}
    for lbl, info in result["coils"].items():
        p = os.path.join(output_dir, f"{lbl}_holder.obj")
        save_obj(info["holder"], p)
        paths[lbl] = p
    return paths


# ─────────────────────────────────────────────────────────────────────────────
# Blender Python script generation
# ─────────────────────────────────────────────────────────────────────────────

def generate_blender_script(result, output_blend_path=None) -> str:
    """Return a self-contained Python script to recreate the scene in Blender.

    The script can be run via:
      blender --background --python script.py
    Or pasted into Blender's Script Editor and executed.
    """
    # Serialise wire paths as a compact embedded dict (nested lists)
    coil_data = {}
    for lbl, info in result["coils"].items():
        coil_data[lbl] = {
            "wires": [{"xyz": w["xyz"].tolist(), "level": w["level"]}
                      for w in info["wires_3d"]],
            "coil_radius_mm": info["coil_radius_mm"],
            "holder": {
                "R": info["holder"].R,
                "R_inner": info["holder"].R_inner,
                "R_outer": info["holder"].R_outer,
                "x_half": info["holder"].x_half,
                "flange_w": info["holder"].flange_w,
                "flange_t": info["holder"].flange_t,
            },
        }
    data_json = json.dumps(coil_data, separators=(",", ":"))

    output_line = ""
    if output_blend_path:
        safe = output_blend_path.replace("\\", "\\\\")
        output_line = f'bpy.ops.wm.save_as_mainfile(filepath=r"{safe}")'

    script = textwrap.dedent(f"""\
    # Gradient Coil Designer — Auto-generated Blender scene
    # Run: blender --background --python <this_file>
    import bpy, json, math
    import numpy as np

    # ── 1. Scene reset ──────────────────────────────────────────────────────
    bpy.ops.object.select_all(action='SELECT')
    bpy.ops.object.delete()
    for block in list(bpy.data.meshes) + list(bpy.data.curves) + list(bpy.data.materials):
        try: bpy.data.meshes.remove(block) if hasattr(block,'vertices') else \
             bpy.data.curves.remove(block) if hasattr(block,'splines') else \
             bpy.data.materials.remove(block)
        except: pass

    # ── 2. Embedded coil data ───────────────────────────────────────────────
    COIL_DATA = json.loads({repr(data_json)})

    WIRE_COLORS = {{
        "Gx": {{"pos": (0.9, 0.3, 0.05, 1.0), "neg": (0.2, 0.4, 0.9, 1.0)}},
        "Gy": {{"pos": (0.05, 0.65, 0.15, 1.0), "neg": (0.6, 0.85, 0.1, 1.0)}},
        "Gz": {{"pos": (0.9, 0.5, 0.0, 1.0),  "neg": (0.95, 0.8, 0.0, 1.0)}},
    }}
    HOLDER_COLORS = {{
        "Gx": (1.0, 0.55, 0.0),
        "Gy": (0.1, 0.65, 0.2),
        "Gz": (0.15, 0.35, 0.9),
    }}

    def make_material(name, color, alpha=1.0):
        mat = bpy.data.materials.new(name)
        mat.use_nodes = True
        bsdf = mat.node_tree.nodes.get("Principled BSDF")
        if bsdf:
            bsdf.inputs["Base Color"].default_value = (*color, 1.0)
            bsdf.inputs["Alpha"].default_value = alpha
            bsdf.inputs["Metallic"].default_value = 0.8
            bsdf.inputs["Roughness"].default_value = 0.2
        mat.blend_method = "BLEND" if alpha < 1.0 else "OPAQUE"
        return mat

    def add_curve_from_path(name, xyz_m, bevel_r_mm, mat, collection):
        # xyz_m is in metres (from our data)
        crv = bpy.data.curves.new(name, type="CURVE")
        crv.dimensions = "3D"
        crv.bevel_depth = bevel_r_mm * 1e-3
        crv.bevel_resolution = 4
        crv.fill_mode = "FULL"
        sp = crv.splines.new("POLY")
        sp.points.add(len(xyz_m) - 1)
        for i, (x, y, z) in enumerate(xyz_m):
            sp.points[i].co = (x, y, z, 1.0)
        obj = bpy.data.objects.new(name, crv)
        obj.data.materials.append(mat)
        collection.objects.link(obj)
        return obj

    def add_cylinder_holder(label, R_inner, R_outer, x_half, flange_w, flange_t, mat, collection):
        # Main cylinder shell via Boolean (solid cylinder minus inner bore)
        # Use simple parametric approach: add_cylinder at OD, subtract ID bore

        # Outer cylinder
        bpy.ops.mesh.primitive_cylinder_add(
            radius=R_outer*1e-3, depth=x_half*2*1e-3, location=(0,0,0),
            vertices=64, end_fill_type='TRIFAN'
        )
        outer = bpy.context.active_object
        outer.name = f"Holder_{{label}}_outer"

        # Inner bore (cutter)
        bpy.ops.mesh.primitive_cylinder_add(
            radius=R_inner*1e-3, depth=x_half*2.1*1e-3, location=(0,0,0),
            vertices=64, end_fill_type='TRIFAN'
        )
        inner = bpy.context.active_object
        inner.name = f"Holder_{{label}}_bore"

        # Boolean difference
        mod = outer.modifiers.new("Bore", "BOOLEAN")
        mod.operation = "DIFFERENCE"
        mod.object = inner
        bpy.context.view_layer.objects.active = outer
        bpy.ops.object.modifier_apply(modifier="Bore")
        bpy.data.objects.remove(inner, do_unlink=True)

        outer.data.materials.append(mat)
        collection.objects.link(outer)
        try: bpy.context.scene.collection.objects.unlink(outer)
        except: pass

        # End flanges
        if flange_w > 0:
            for sign in (-1, 1):
                x_pos = sign * (x_half + flange_w/2)
                bpy.ops.mesh.primitive_cylinder_add(
                    radius=(R_outer+flange_t)*1e-3,
                    depth=flange_w*1e-3,
                    location=(0, 0, x_pos*1e-3),
                    vertices=64, end_fill_type='TRIFAN'
                )
                # Blender default: cylinder axis = Z; rotate to X axis
                flange = bpy.context.active_object
                flange.name = f"Flange_{{label}}_{{'+' if sign>0 else '-'}}"
                # bore out inner
                bpy.ops.mesh.primitive_cylinder_add(
                    radius=R_inner*1e-3, depth=flange_w*1.1*1e-3,
                    location=(0, 0, x_pos*1e-3), vertices=64
                )
                fcutter = bpy.context.active_object
                bpy.context.view_layer.objects.active = flange
                fmod = flange.modifiers.new("FBore","BOOLEAN")
                fmod.operation = "DIFFERENCE"
                fmod.object = fcutter
                bpy.ops.object.modifier_apply(modifier="FBore")
                bpy.data.objects.remove(fcutter, do_unlink=True)
                flange.data.materials.append(mat)
                collection.objects.link(flange)
                try: bpy.context.scene.collection.objects.unlink(flange)
                except: pass

        return outer

    # ── 3. Build scene ──────────────────────────────────────────────────────
    # Note: Blender default is Z-up. Our data uses X=bore axis, Y=B0, Z=perp.
    # We'll import as-is (rotate scene view in Blender if preferred).

    scene_col = bpy.context.scene.collection

    for label, data in COIL_DATA.items():
        wire_col = bpy.data.collections.new(f"{{label}}_Wires")
        scene_col.children.link(wire_col)
        holder_col = bpy.data.collections.new(f"{{label}}_Holder")
        scene_col.children.link(holder_col)

        cols = WIRE_COLORS[label]
        wire_r_mm = 0.75   # visual wire tube radius

        for i, wd in enumerate(data["wires"]):
            xyz = wd["xyz"]   # already in metres
            level = wd["level"]
            name = f"{{label}}_wire_{{i:02d}}"
            color = cols["pos"][:3] if level > 0 else cols["neg"][:3]
            mat = make_material(name + "_mat", color)
            add_curve_from_path(name, xyz, wire_r_mm, mat, wire_col)

        # Holder
        h = data["holder"]
        hcol = tuple(HOLDER_COLORS[label])
        hmat = make_material(f"Holder_{{label}}_mat", hcol, alpha=0.45)
        add_cylinder_holder(
            label,
            h["R_inner"], h["R_outer"], h["x_half"],
            h["flange_w"], h["flange_t"],
            hmat, holder_col
        )

    # ── 4. Camera + lighting ────────────────────────────────────────────────
    bpy.ops.object.camera_add(location=(0.4, -0.4, 0.3))
    cam = bpy.context.active_object
    cam.rotation_euler = (math.radians(70), 0, math.radians(45))
    bpy.context.scene.camera = cam

    bpy.ops.object.light_add(type='SUN', location=(0.5, -0.5, 0.8))
    sun = bpy.context.active_object
    sun.data.energy = 3.0

    bpy.ops.object.light_add(type='AREA', location=(-0.3, 0.3, 0.5))
    area = bpy.context.active_object
    area.data.energy = 200.0

    bpy.context.scene.render.engine = 'CYCLES'
    bpy.context.scene.cycles.samples = 64

    print("Gradient coil scene built successfully.")

    # ── 5. Save ──────────────────────────────────────────────────────────────
    {output_line}
    """)
    return script


def save_blender_script(result, script_path):
    """Write the Blender import script to a .py file."""
    script = generate_blender_script(result)
    with open(script_path, "w", encoding="utf-8") as f:
        f.write(script)
    return script_path


# ─────────────────────────────────────────────────────────────────────────────
# Headless Blender .blend export
# ─────────────────────────────────────────────────────────────────────────────

def find_blender():
    """Return path to Blender executable, or None if not found."""
    for p in BLENDER_PATHS:
        if os.path.isfile(p):
            return p
        try:
            r = subprocess.run([p, "--version"], capture_output=True, timeout=5)
            if r.returncode == 0:
                return p
        except Exception:
            pass
    return None


def export_blend(result, blend_path, blender_exe=None, timeout=120,
                 progress_callback=None):
    """Generate a .blend file by running Blender headlessly.

    Parameters
    ----------
    result : dict
        Output of GradientCoilDesigner.run().
    blend_path : str
        Output .blend file path.
    blender_exe : str or None
        Path to blender.exe / blender binary.  Auto-detected if None.
    timeout : int
        Max seconds to wait for Blender.
    progress_callback : callable(str) or None
        Called with status strings during export.

    Returns
    -------
    str  — path to the written .blend file
    Raises RuntimeError if Blender is not found or fails.
    """
    def log(msg):
        if progress_callback:
            progress_callback(msg)
        else:
            print(msg)

    if blender_exe is None:
        blender_exe = find_blender()
    if blender_exe is None:
        raise RuntimeError(
            "Blender not found.  Install Blender or set blender_exe= manually."
        )

    log(f"Using Blender: {blender_exe}")
    os.makedirs(os.path.dirname(os.path.abspath(blend_path)), exist_ok=True)

    # Write script to a temp file
    script = generate_blender_script(result, output_blend_path=blend_path)
    with tempfile.NamedTemporaryFile(suffix=".py", delete=False,
                                     mode="w", encoding="utf-8") as tf:
        tf.write(script)
        script_file = tf.name

    log("Running Blender headlessly ...")
    try:
        proc = subprocess.run(
            [blender_exe, "--background", "--python", script_file],
            capture_output=True, text=True, timeout=timeout,
        )
        if proc.returncode != 0:
            raise RuntimeError(
                f"Blender exited with code {proc.returncode}.\n"
                f"stderr: {proc.stderr[-2000:]}"
            )
        log(f"Blend file written: {blend_path}")
    finally:
        try:
            os.unlink(script_file)
        except OSError:
            pass

    return blend_path
